locallibrary/catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name="book-detail"),
    path('book/<int:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name="author_create"),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name="author-detail")
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('catalog/', include('catalog.urls'))
]
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    """
    Модель представляющая жанр книги (Научная фантастика, Комедия, Триллер и т.д)
    """
    name = models.CharField(max_length=200, help_text="Введите жанр книги")

    def __str__(self):
        """
        Строка представляющая модель Таблицы в административной панеле
        :return: имя жанра
        """
        return self.name


class Language(models.Model):
    """
    Модель представляющая язык книги (Русский, Французский и т.д)
    """
    LANGUAGE_CHOICES = (
        ("ru", "Russian"),
        ("fr", "French"),
        ("de", "Germany"),
        ("en", "English"),
    )
    name = models.CharField(max_length=2, choices=LANGUAGE_CHOICES)

    def get_absolute_url(self):
        """
        :return: Возращает url-адресс для доступа к определенному экземпляру языка
        """
        return reverse('language-detail', args=[str(self.id)])

    def __str__(self):
        """
        :return: Строка представляющая модель таблицы
        """
        return self.name


class Book(models.Model):
    """
    Модель представляющая книгу (но не конкретный экземпляр книги)
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Введите краткое описание книги")
    isbn = models.CharField("ISBN", max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN'
                                      'number</a>')
    genre = models.ManyToManyField(Genre, help_text="Выберите жанр книги")
    language = models.ForeignKey('Language', null=True,
                                 help_text="Введите язык желаемой книги", on_delete=models.SET_NULL)

    def __str__(self):
        """
        Строка представляющая модель таблицы
        :return: Заголовок книги
        """
        return self.title

    def display_genre(self):
        """
        Создает строку для Жанров. Это обязательно для отображения жанров в панеле Администраторов в Django
        :return: Строка жанров
        """
        return ', '.join([genre.name for genre in
                          self.genre.all()[:3]])

    display_genre.short_description = "Genre"

    def get_absolute_url(self):
        """
        :return: Возращает url-адресс для доступа к определенному экземпляру книги
        """
        return reverse("book-detail", args=[str(self.id)])


class BookInstance(models.Model):
    """
    Модель представляющая конкретный экземпляр книги (ту которую можно взять из библеотеки)
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Уникальный индефикатор для этой конкретной книги во всей библеотеки")
    book = models.ForeignKey("Book", on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reversed'),
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m',
                              help_text="Забронировать книгу")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['due_back']
        permissions = (
            ('can_mark_returned', 'Set book as returned.'),
        )

    def __str__(self):
        """
        :return: Строка представляющая модель объекта
        """
        return '%s (%s)' % (self.id, self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    """
    Модель представляющая автора
    """
    first_name = models.CharField(max_length=100, verbose_name='first_name')
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    def get_absolute_url(self):
        """
        :return: Возращает url-адресс для доступа к определенному экземпляру автора
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        :return: Строка представляющая модель объекта
        """
        return '%s, %s' % (self.last_name, self.first_name)

locallibrary/catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Введите дату между текущим днем и 4 неделями(по умолчанию 3)")

    def clean_renewal_date(self):
        data = self.cleaned_data["renewal_date"]
        # проверка того, что дата не в прошлом
        if data < datetime.date.today():
            raise ValidationError(_("Неправильная дата, возрат в прошлом"))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_("Неправильная дата, дата не может превышать 4 недели"))

        if data == datetime.date.today():
            raise ValidationError(_("Вы не можете вернуть книгу в тот же день что и взяли"))

        return data

locallibrary/catalog/views.py
from django.shortcuts import render
from .models import Book, BookInstance, Author, Genre
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from .forms import RenewBookForm
from django.contrib.auth.decorators import permission_required
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    """
    Функция для отображения для домашней страницы сайта
    :param request:
    :return:
    """
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Доступные книги в статусе "a"
    available_genres = Genre.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    return render(request, 'index.html', context={
        'num_books': num_books, 'num_instances': num_instances, 'num_instance_available': num_instances_available,
        'num_authors': num_authors, "num_visits": num_visits
    })


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk=pk)
    # Если данный метод это POST запрос, тогда
    if request.method == "POST":
        # создаем экземпляр формы и заполняем данными из запроса (связывание)
        form = RenewBookForm(request.POST)
        # Проверка подлинности формы
        if form.is_valid():
            # обработка данных из form.cleaned_data
            # здесь просто присваем данные формы их полю due_back
            book_inst.due_back = form.cleaned_data["renewal_date"]
            book_inst.save()

            # Переход по новому адрессу
            return HttpResponseRedirect(reverse('index'))
    # Если это GET запрос, создать форму по умолчанию
    else:
        proposed_renewal_date = datetime.datetime.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={"renewal_date": proposed_renewal_date})
        return render(request, 'catalog/book_renew_librarian.html',
                      {"form": form, "bookinst": book_inst})


class BookListView(generic.ListView):
    model = Book

    # def get_queryset(self):
    #     return


class BookDetailView(generic.DetailView):
    model = Book


class AuthorDetailView(generic.DetailView):
    model = Author


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10


class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'
    initial = {"date_of_birt": "12/10/2020"}


class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', "last_name", 'date_of_birth', "date_of_death"]


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Общий просмотр на основе классов со списком книг, которые можно одолжить текущему пользователю
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Удалить Автора</h1>

  <p>Вы действительно хотите удалить автора: {{ author }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

<p><strong>Имя автора:</strong> <a href="">{{ author.first_name }}</a></p> <!-- author detail link not yet defined -->
<p><strong>Фамилия автора:</strong> {{ author.last_name }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Дата рождения:</strong> {{ author.date_of_birth }}</p>
{% if author.date_of_death %}
<p><strong>Дата смерти:</strong> {{ author.date_of_death }}</p>
{% else %}
            <p><strong>Автор жив:</strong></p>
{% endif %}

{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
 <h1>Список Авторов</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <div>
            <p><strong>Имя:</strong><a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a></p>
            <p><strong>Фамилия:</strong> {{ author.last_name }}</p>
            <p><strong>Дата рождения:</strong> {{ author.date_of_birth }}</p>
            {% if author.date_of_death %}
            <p><strong>Дата смерти:</strong> {{ author.date_of_death }}</p>
            {% else %}
                        <p><strong>Автор жив:</strong></p>
            {% endif %}
        </div>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
</div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
 <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
          {% if perms.catalog.can_mark_returned %}-
  <a href="{% url 'renew-book-librarian' book.id %}">Вернуть кингу</a>
{% endif %}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Возращает: {{bookinst.book.title}}</h1>
    <p>Кто возращает книгу: {{bookinst.borrower}}</p>
    <p>{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'base_generic.html' %}

{% block content %}

<h1>Занятые книги</h1>

{% if bookinstance_list %}
<ul>

    {% for books in bookinstance_list %}
    <li class="{% if books.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' books.book.pk %}">
            {{ books.book.title }}
        </a>
        ({{ books.due_back }})
    </li>
    {% endfor %}
</ul>

{% else %}

<p>
    У вас нет занятых книг
</p>
{% endif %}

{% endblock %}